---
#
# install/run filebeat elk client
#

- name: Ubuntu - Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Ubuntu - Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present
  
 
- name: Ubuntu - Install filebeat 
  apt: name={{ item }} state=present
  become: true
  with_items:
    - filebeat

- name: Generate filebeat configuration template
  template:
    src=filebeat.yml.j2
    dest=/etc/filebeat/filebeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  register: filebeat_needs_restart

- name: Check ELK server SSL client certificate
  stat: path=/etc/ssl/certs/filebeat-forwarder.crt
  ignore_errors: true
  register: elk_client_ssl_cert_exists
  

- name: Install ELK server SSL client certificate
  get_url:
    url=http://{{ groups['elk_servers'][0] }}:{{ elk_server_ssl_cert_port }}/filebeat-forwarder.crt
    dest=/etc/filebeat/filebeat-forwarder.crt
  become: true
  when: elk_client_ssl_cert_exists != 0

- name: Install ELK server SSL client certificate
  get_url:
    url=http://{{ groups['elk_servers'][0] }}:{{ elk_server_ssl_cert_port }}/filebeat-forwarder.key
    dest=/etc/filebeat/filebeat-forwarder.key
  become: true
  when: elk_client_ssl_cert_exists != 0

- name: Start filebeat service
  command: systemctl start filebeat.service
  ignore_errors: true
  become: true
  when: filebeat_needs_restart != 0

- name: Setup filebeat service
  service: name=filebeat state=started enabled=true
  become: true
  

