---


- name: Include specific filebeat
  include: filebeat-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include specific filebeat
  include: filebeat-redhat.yml
  when: ansible_os_family == 'RedHat'

