---


- name: Include specific logstash
  include: logstash-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include specific logstash
  include: logstash-redhat.yml
  when: ansible_os_family == 'RedHat'

