---

- name: Include specific nginx
  include: nginx-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include specific nginx
  include: nginx-redhat.yml
  when: ansible_os_family == 'RedHat'

