---

- hosts: all
  remote_user: vagrant
  become: yes
  roles:
  - common

- name: Install FreeIPA role
  hosts: freeipa_masters
  remote_user: vagrant
  become: yes
  roles:
     - ipaserver


- name: Enroll FreeIPA clients
  hosts: freeipa_clients
  remote_user: vagrant
  become: yes
  roles:
     - ipaclient

- name: Install Aker 
  hosts: aker_servers
  remote_user: vagrant
  become: yes
  roles:
     - aker

