---


- name: Include specific kibana
  include: kibana-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include specific kibana
  include: kibana-redhat.yml
  when: ansible_os_family == 'RedHat'

