---


- name: Include specific Elasticsearch
  include: elasticsearch-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include specific Elasticsearch
  include: elasticsearch-redhat.yml
  when: ansible_os_family == 'RedHat'

