---
- name: Hard set the hostname
  hostname: name={{ ansible_fqdn }}


- name: Remove localhost entry
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1.*{{ ansible_fqdn }}.*$'
    state: absent
    
- name: Add /etc/hosts entry
  lineinfile:
    dest=/etc/hosts
    regexp=" {{ ansible_hostname }} "
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
    owner=root
    group=root
    mode=0644

- name: Install FreeIPA server packages (yum)
  yum: name={{ item }} state=present
  with_items: ipaserver_packages
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int <= 21

- name: Install FreeIPA server packages (dnf)
  dnf: name={{ item }} state=present
  with_items: "{{ ipaserver_packages }}"
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int > 21

- name: Install FreeIPA server packages (yum/CentOS)
  package: name={{ item }} state=present
  with_items: "{{ centos_ipaserver_packages }}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  
- name: Install FreeIPA server packages (apt-get)
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ ubuntu_ipaserver_packages }}"
  when: ansible_distribution == "Ubuntu"
    
- name: Install FreeIPA server (takes 5-7 mins)
  action: command
    {{ ipaserver_base_command }}
    --realm {{ ipaserver_realm }}
    --domain {{ ipaserver_domain }}
    -a {{ ipaserver_admin_password }}
    -p {{ ipaserver_dir_admin_password }}
    --hostname={{ ansible_fqdn }}
    --ip-address={{ ansible_default_ipv4.address }}
    {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart | default(False) else '' }}
    {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax | default(False) else '' }}
    {{ '--forwarder=%s' % dns
       if dns | default(False) else '--no-forwarders' }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }}
    {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }}
    {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }}
    {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }}
    {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }}
    creates=/etc/ipa/default.conf

- name: Set default shell to /bin/bash
  ipa:
    args="config-mod --defaultshell=/bin/bash"
    password="{{ ipaserver_admin_password }}"
    ignore_no_modifications=true
    ignore_already_exists=true
  ignore_errors: True
  
- include: firewalld.yml
  when: 
    - ipaserver_manage_firewalld == True
    - ansible_os_family == "RedHat"

- include: ufw.yml
  when: 
    - ipaserver_manage_firewalld == True
    - ansible_distribution == "Ubuntu"
