---
- name: Install ufw
  apt: package=ufw state=present

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart ufw

- name: Configure ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'allow', port: '22', proto: 'tcp' }
    - { rule: 'allow', port: '80', proto: 'tcp' }
    - { rule: 'allow', port: '443', proto: 'tcp' }
    - { rule: 'allow', port: '88', proto: 'tcp' }
    - { rule: 'allow', port: '636', proto: 'tcp' }
    - { rule: 'allow', port: '389', proto: 'tcp' }
    - { rule: 'allow', port: '464', proto: 'tcp' }
    - { rule: 'allow', port: '88', proto: 'udp' }
    - { rule: 'allow', port: '123', proto: 'udp' }
    - { rule: 'allow', port: '53', proto: 'udp' }
    
  notify:
    - restart ufw

- name: Enable ufw logging
  ufw: logging=on
  notify:
    - restart ufw

- name: Enable ufw
  ufw: state=enabled
